### ISSUE TITLE
Building and publishing modules

### ISSUE THREAD

**Issue by galleon** [visgl/deck.gl#2784]
- Suggest an improvement or clarification in our documentation. -

Hello
First thanks for this great framework.
I am trying to build (and publish) the latest version from the different modules.
I am using yarn & have been doing the `yarn bootstrap`

I am now trying to publish my own lib but face the following error:

modules/core > yarn prepublishOnly
...
> @deck.gl/core@7.0.0-alpha.4 build-bundle /Users/alleon_g/0x-TechWork/deck.gl/modules/core
> webpack --config ../../scripts/bundle.config.js

/Users/alleon_g/0x-TechWork/deck.gl/node_modules/webpack-cli/bin/cli.js:231
				throw err;
				^

Error: Cannot find module '../aliases'

**Comment by Pessimistress** [comment]
This was fixed in https://github.com/uber/deck.gl/pull/2777.

The latest master is regularly published as 7.0.0-alpha.x. A lot of features are still WIP so issues are expected.

**Comment by galleon** [comment]
Thanks.
It works much better.
I still have a problem publishing on my npm registry. A  `yarn publish`gives me a Scope not found (like here https://github.com/yarnpkg/yarn/issues/3700)
What is your $HOME/.yarnrc syntax looks like for the scoped registry ?

**Comment by galleon** [comment]
Hi @Pessimistress, there is still a problem I have not solved. My app is requiring something which is not yet in a published release (not yet in 7.0.0-alpha.4).
I have locally cloned the repo then:
`yarn bootstrap`
`cd modules/core; yarn prepublishOnly`  and so on for each modules

My goal is then to use those versions in my project.
For this I tried first to publish in my private registry but I do not own `@deck.gl`;-)
Then I tried this:
`yarn add file:/Users/alleon_g/0x-TechWork/deck.gl/modules/core/`without success

`yarn add v1.13.0
[1/4] 🔍  Resolving packages...
error Couldn't find package "luma.gl@^7.0.0-alpha.14" required by "file:/Users/alleon_g/0x-TechWork/deck.gl/modules/core/" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
``
What is the appropriate to implement this use-case?
