### ISSUE TITLE
Help on DeckGL performance

### ISSUE THREAD

**Issue by txtl** [visgl/deck.gl#4989]
Hi all,

I'm trying some performance tests by constructing two tests with 100,000 icons. One is with 100,000 icon changes and one without any change besides the trigger. I don't see any difference in performance between the two. Is that what it's supposed to be?

I demonstrated the two scenarios here: 

1. No change besides the trigger: 
https://codepen.io/txtl-smith/pen/gOrdKjK

2. 100,000 changes and trigger
https://codepen.io/txtl-smith/pen/oNxOgqG

The data props is not changed in both cases. 

Do you have suggestions to improve performance in the case of only 1 icon change out of 100,000 icons?

Thanks,

**Comment by TextTL** [comment]
I read that _dataDiff may be helpful, but I don't know how to use _dataDiff. I tried to go through the document, but I'm not so clear on how to get oldData and newData because the data props was not changed.

**Comment by Pessimistress** [comment]
> I don't see any difference in performance between the two

deck.gl does not track if your data is actually changed. When updateTrigger changes, `getIcon` is called 100,000 times, which is the perf bottleneck.

[_dataDiff](https://deck.gl/docs/api-reference/core/layer#_datadiff)

**Comment by txtl** [comment]
I added the following to my code to tell deckgl that getIcon is changed, but only at these indices to see if _dataDiff makes any difference. 
```
   const iconLayer = new IconLayer({
        id: "icon-layer",
        data: testdata,
        dataComparator: (newData, oldData) => false,
        _dataDiff: (newData, oldData) => {
          return [{
            startRow: 1,
            endRow: 2
          }]
        },
```
and I don't see any improvement. I may have misunderstood _dataDiff, 

https://codepen.io/txtl-smith/pen/gOrdKjK

**Comment by Pessimistress** [comment]
- You should remove `updateTrigger` if you use `_dataDiff`. `updateTrigger.getIcon` will invalidate all icons regardless of whether data has changed.
- `_dataDiff` is an experimental prop and may not work with `IconLayer` at the moment. I will investigate.

**Comment by txtl** [comment]
Thank you! I close this issue.

**Comment by Pessimistress** [comment]
Fix is landed in 8.2.10

**Comment by txtl** [comment]
I tried https://unpkg.com/deck.gl@8.2.10/dist.min.js, and I did not see any improvement. The previous codepen still shows the same result: 
```
var {
      COORDINATE_SYSTEM,
      OrthographicView,
      Deck,
      IconLayer,
    } = deck;
    const INITIAL_VIEW_STATE = {
      target: [500, 200, 0],
      zoom: 1,
    };

    const deckgl = new Deck({
      initialViewState: INITIAL_VIEW_STATE,
      controller: true,
      views: [new OrthographicView()],
      layers: [],
    });


    let url = "https://raw.githubusercontent.com/txtl/deckgl/main/symbol.json";
    var testdata;

    var stats = new Stats();
    stats.showPanel(0); // 0: fps, 1: ms, 2: mb, 3+: custom
    document.body.appendChild(stats.dom);

    function loadData(url) {
      var xmlhttp = new XMLHttpRequest();
      xmlhttp.onreadystatechange = function () {
        if (this.readyState == 4 && this.status == 200) {
          testdata = JSON.parse(this.responseText);
          testdata.forEach(el => {
            el.symbol_id = "marker-100";
          })
          animate();
        }
      };
      xmlhttp.open("GET", url, true);
      xmlhttp.send();
    }


    function _deckgl_render() {

      const iconLayer = new IconLayer({
        id: "icon-layer",
        data: testdata,
         dataComparator: (newData, oldData) => false,
        _dataDiff: (newData, oldData) => {
          return [{
            startRow: 1,
            endRow: 5
          }]},
        iconMapping: "https://raw.githubusercontent.com/visgl/deck.gl/master/examples/website/icon/data/location-icon-mapping.json",
        iconAtlas: "https://raw.githubusercontent.com/visgl/deck.gl/master/examples/website/icon/data/location-icon-atlas.png",
        getPosition: (d) => d.position,
        getIcon: (d) => d.symbol_id,
        getSize: (d) => 24,
      });

      deckgl.setProps({
        layers: [iconLayer],
      });

    }

    function animate() {
      requestAnimationFrame(animate);
      
      stats.begin();
      _deckgl_render();
      stats.end();

    }
    loadData(url);
```
codepen: https://codepen.io/txtl-smith/pen/gOrdKjK

**Comment by txtl** [comment]
I've just found that with the fix for IconLayer in 8.2.10, _dataDiff just redraw the range returned from _dataDiff, but somehow, GPU usage is the same as redrawing the whole buffer.

**Comment by Pessimistress** [comment]
That is correct. Each redraw the whole context is wiped. If you want to reduce GPU usage you need to reduce the number of layers/objects on screen.

**Comment by txtl** [comment]
I'm trying to understand the performance of DeckGL so that I can manage large datasets for the best drawing performance. Did you mean that if I divide 100,000 icons into 4 layers, and if changes are made to one layer, deckgl has to redraw all 4 layers? Does this mean that the only benefit of separating into layers is to reduce attribute computation every life cycle?

Thank you very much!

**Comment by txtl** [comment]
I tested this https://codepen.io/txtl-smith/pen/gOrdKjK on my laptop and Desktop

My laptop: 
CPU: i5 1035G4
Graphic: Integrated Intel (R) Irus (R) plus
FPS: 4
GPU load: 80-90%
Browsers: 

My desktop: 
CPU: i7-6700 
Graphic: GeForce GT 1030
FPS: 10
GPU load: 95-99%

``
Microsoft Edge | 85.0.564.68 (Off`icial build) (64-bit)
-- | --
Revision | 226c9a618a11c00d61ee433fede8d2eef5d27985
Operating system | Windows 10 OS Version 2004 (Build 19041.508)
JavaScript | V8 8.5.210.26
```

and

Google Chrome | 85.0.4183.121 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | a81aa729a8e1fd413943a339393c82e7b8055ddc-refs/branch-heads/4183@{#1864}
OS | Windows 10 OS Version 2004 (Build 19041.508)
JavaScript | V8 8.5.210.26

```
```

**Comment by Pessimistress** [comment]
If you disable the animation and just pan the map around you should see similar frame rate, suggesting the perf bottleneck is drawing, not the data update.

Icons could be heavier to render than e.g. scatterplot because each icon samples from a texture. Realistically you should not need to draw all 100K in one viewport, because the user will not be able to read them anyways. Zoom way in to see part of your data, or make the icons smaller, and you should see better FPS. You can also explore clustering them like the IconLayer example on the deck.gl website.

**Comment by txtl** [comment]
When I disabled the animation, I saw a similar framerate. It's not the data update because when I looked at the per thread, the CPU is very low, while GPU is reaching max. I've just run the same test on another machine with GTX 1080, the FPS is 45, while the GPU load is  40%. I think the data bus would play a major role here. 

The application will be a very large wall of displays; each machine shall drive 6-10 8K displays. This test is just to understand the performance behavior of Deck.GL for better planning of data partitioning and data updates rate. I ran this test on low-end machines for that purpose. 

Thank you very much for your support!

**Comment by Pessimistress** [comment]
At this scale the main reason of your perf lag is the screen resolution. GPU load is proportional to the pixels that you are trying to render. You can try reduce the rendering buffer size with `useDevicePixels: 1`. I'm afraid I don't have better suggestions because this is not a scenario people normally use a web browser for. You may see if [deck.gl-native](https://github.com/UnfoldedInc/deck.gl-native) works a little better.

**Comment by txtl** [comment]
useDevicePixels: 1 boosts FPS. even though window.devicePixelRatio are  1.3 - 1.5 on my displays. 

Thanks so much for this!
