### ISSUE TITLE
[Bug] Interleaving error after upgrading from 8.8 to 8.9

### ISSUE THREAD

**Issue by arthurgailes** [visgl/deck.gl#7818]
### Description

Hello,

Using 8.9.7, setting interleaved to true while using react-map-gl causes the following errors:
1. deck.gl layers disappear
2. The map crashes when re-rendering with the following error: "can't access property "stop", this.animationLoop is null"

I updated directly from 8.8 to 8.9.7, so this could've occurred at any point in the interim.

**Edit**: The break occurs somewhere between 8.8.13 (where it works) and 8.8.27

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

 https://codesandbox.io/s/deckgl-interleaving-8-9-jyb8pl

```
export function App() {
  const [viewState, setViewState] = useState({
    latitude: 40,
    longitude: -74.5,
    zoom: 12
  });
  const onMoveEnd = useCallback(
    debounce(({ viewState }) => {
      setViewState(viewState);
    }, 1000),
    []
  );

  const scatterplotLayer = new ScatterplotLayer({
    id: "my-scatterplot",
    data: [{ position: [-74.5, 40], size: 100 }],
    getPosition: (d) => d.position,
    getRadius: (d) => d.size,
    getFillColor: [255, 0, 0]
  });

  return (
    <Map
      initialViewState={viewState}
      onMoveEnd={onMoveEnd}
      style={{ width: "100vw", height: "100vh" }}
      terrain={{ source: "mapbox-dem", exaggeration: 1 }}
      mapStyle="mapbox://styles/mapbox/light-v9"
      mapboxAccessToken="API_KEY"
    >
      <DeckGLOverlay layers={[scatterplotLayer]} interleaved={true} />
    </Map>
  );
}
```

### Environment

- Framework version:
- Browser:
- OS:

**Comment by Pessimistress** [comment]
It might be caused by React StrictMode (removing the overlay before deck is initialized).

**Comment by arthurgailes** [comment]
Thank you. Yes, removing strict mode solves the issue. Is there any other workaround? Strict mode didn't cause any problems before 8.8.13.

https://codesandbox.io/s/deckgl-interleaving-8-9-jyb8pl

**Comment by arthurgailes** [comment]
Fixed by #7821

**Comment by akre54** [comment]
I'm also still seeing this issue and confirmed that removing strict mode is the hotfix. Is the patch released?

**Comment by Pessimistress** [comment]
The fix is included in v8.9.16.
