### ISSUE TITLE
Warning message from @luma.gl

### ISSUE THREAD

**Issue by ariel-upstream** [visgl/deck.gl#8825]
Hi,
In my React project after updating the version of Deck.gl to:   "deck.gl": "9.0.9",
I'm getting the warning from: @luma.gl

`WARNING in ./node_modules/@luma.gl/shadertools/dist/libs/wgsl-reflect/wgsl_reflect.module.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '.../node_modules/@luma.gl/shadertools/dist/libs/wgsl-reflect/wgsl_reflect.module.js.map' file: Error: ENOENT: no such file or directory, open '/.../node_modules/@luma.gl/shadertools/dist/libs/wgsl-reflect/wgsl_reflect.module.js.map'`

### Flavors

- [ ] Script tag
- [x] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

No warning 

### Steps to Reproduce

Updating Deck.gl version

### Environment

  "deck.gl": "9.0.10",

**Comment by ibgreen** [comment]
This is fixed on master (9.1) by using to the now official published wgsl-reflect module. I suppose this could be back-ported to 9.0.

**Comment by yonghah** [comment]
This issue still exists. Do we need to bump luma.gl version to 9.1?

**Comment by ibgreen** [comment]
luma.gl@9.0.16
