### ISSUE TITLE
[Bug] Layers flickering when resizing window/canvas

### ISSUE THREAD

**Issue by erlend-skarpnes** [visgl/deck.gl#9918]
### Description

When the browser window/canvas is resized, the layers in the map flicker as they are redrawn. Tested in `get-started/react/basic` and `get-started/pure-js/basic`. Does not happen on versions < 9.2.0.

While the use-case of slowly resizing the browser window is not the most needed feature, it also happens during resizing of the canvas (which our application does), and when that resizing happens as part of an animation, the flickering is quite annoying.

### Flavors

- [x] Script tag
- [x] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CARTO
- [ ] ArcGIS

### Expected Behavior

Layers do not flicker when resizing the canvas, for example by keeping the old layers on screen until the new layers are drawn.

### Steps to Reproduce

On any example running deckgl > 9.2, resize the browser window, and see that all the layers flicker. Extra annoying on maps without maptiles (the basic examples), as the entire screen flicker.

### Environment

- Framework version: deck.gl@9.2.0
- Browser: Firefox 146.0
- OS: macOS 26.2

**Comment by albertogonzalezartavia-dot** [comment]
> ### Descripción
> Al redimensionar la ventana/lienzo del navegador, las capas del mapa parpadean al redibujarse. Probado en `get-started/react/basic`y `get-started/pure-js/basic`. No ocurre en versiones anteriores a la 9.2.0.
> 
> Si bien el caso de uso de cambiar lentamente el tamaño de la ventana del navegador no es la característica más necesaria, también sucede durante el cambio de tamaño del lienzo (lo que hace nuestra aplicación), y cuando ese cambio de tamaño ocurre como parte de una animación, el parpadeo es bastante molesto.
> 
> ### Sabores
> * [x] Etiqueta de script[x] Reaccionar[ ] Cuaderno de Python/Jupyter[ ] Superposición de Mapbox[ ] Superposición de GoogleMaps[ ] CARTO[ ] ArcGIS
> 
> ### Comportamiento esperado
> Las capas no parpadean al cambiar el tamaño del lienzo, por ejemplo, manteniendo las capas antiguas en la pantalla hasta que se dibujen las nuevas.
> 
> ### Pasos para reproducir
> En cualquier ejemplo con deckgl > 9.2, al cambiar el tamaño de la ventana del navegador, se observa que todas las capas parpadean. Esto resulta especialmente molesto en mapas sin teselas (los ejemplos básicos), ya que toda la pantalla parpadea.
> 
> ### Ambiente
> * Versión del marco: deck.gl@9.2.0
> * Navegador: Firefox 146.0
> * Sistema operativo: macOS 26.2
> 
> ### Registros
> _Sin respuesta_

**Comment by ibgreen** [comment]
Thanks for reporting. 

Comments for maintainers:
- Not sure if this is related, but I had a flickering issue in luma.gl 9.2 that was solved by this PR https://github.com/visgl/luma.gl/pull/2435.
- deck.gl does some of its own resize handling so if this turns out to be the same cause, deck may choose to either try to rely on luma.gl's resize handling, or take similar steps.

**Comment by chrisgervang** [comment]
[v9.2.3](https://github.com/visgl/deck.gl/releases/tag/v9.2.3) had related canvas resize fixes for map overlay integrations, however the flickering is still reproducible in all website examples https://deck.gl/examples 

@ibgreen that flickering fix isn't released in 9.2 - is it feasible to back port it, or does it rely on too many changes coming in 9.3?

**Comment by chrisgervang** [comment]
Investigating this more with https://github.com/visgl/deck.gl/pull/9892 - it appears interleaved rendering doesn't flicker. Render draw calls in interleaved are delegated to the basemap library, still investigating
